export function generateStaticDoc(comp) {
  const propLines = comp.props?.length
    ? comp.props
        .map((p) => `- \`${p.name}\`: ${p.type || 'unknown'}`)
        .join('\n')
    : '_No props documented._';

  return `
  ### 📦 ${comp.name}
  **Path**: \`${comp.filePath}\`
  **Size**: ${comp.sizeKb?.toFixed(2)} KB
  
  ${propLines}
  
  ---
  _Autogenerated by PropCreep Insight (static mode)_
    `.trim();
}
